 
-- Users 1-5 already exist in the DB.
-- All contacts are assigned to Users 1-3 (Rick, Sam, John)
-- for stability since their IDs won't change.
-- ============================================
-- Passwords are plain text for testing only.
-- The API handles hashing via password_hash() in PHP.
-- ============================================

INSERT INTO Users (FirstName, LastName, Login, Password) VALUES
('Alice', 'Johnson', 'AliceJ', 'Pass001'),
('Bob', 'Williams', 'BobW', 'Pass002'),
('Carol', 'Brown', 'CarolB', 'Pass003'),
('David', 'Jones', 'DavidJ', 'Pass004'),
('Emma', 'Garcia', 'EmmaG', 'Pass005'),
('Frank', 'Miller', 'FrankM', 'Pass006'),
('Grace', 'Davis', 'GraceD', 'Pass007'),
('Henry', 'Rodriguez', 'HenryR', 'Pass008'),
('Irene', 'Martinez', 'IreneM', 'Pass009'),
('Jack', 'Hernandez', 'JackH', 'Pass010'),
('Karen', 'Lopez', 'KarenL', 'Pass011'),
('Leo', 'Gonzalez', 'LeoG', 'Pass012'),
('Maria', 'Wilson', 'MariaW', 'Pass013'),
('Nathan', 'Anderson', 'NathanA', 'Pass014'),
('Olivia', 'Thomas', 'OliviaT', 'Pass015'),
('Paul', 'Taylor', 'PaulT', 'Pass016'),
('Quinn', 'Moore', 'QuinnM', 'Pass017'),
('Rachel', 'Jackson', 'RachelJ', 'Pass018'),
('Steve', 'Martin', 'SteveM', 'Pass019'),
('Tina', 'Lee', 'TinaL', 'Pass020'),
('Ulysses', 'Perez', 'UlyssesP', 'Pass021'),
('Vera', 'Thompson', 'VeraT', 'Pass022'),
('Walter', 'White', 'WalterW', 'Pass023'),
('Xena', 'Harris', 'XenaH', 'Pass024'),
('Yusuf', 'Sanchez', 'YusufS', 'Pass025'),
('Zoe', 'Clark', 'ZoeC', 'Pass026'),
('Adam', 'Ramirez', 'AdamR', 'Pass027'),
('Bella', 'Lewis', 'BellaL', 'Pass028'),
('Carlos', 'Robinson', 'CarlosR', 'Pass029'),
('Diana', 'Walker', 'DianaW', 'Pass030'),
('Ethan', 'Young', 'EthanY', 'Pass031'),
('Fiona', 'Allen', 'FionaA', 'Pass032'),
('George', 'King', 'GeorgeK', 'Pass033'),
('Hannah', 'Wright', 'HannahW', 'Pass034'),
('Ivan', 'Scott', 'IvanS', 'Pass035'),
('Julia', 'Torres', 'JuliaT', 'Pass036'),
('Kevin', 'Nguyen', 'KevinN', 'Pass037'),
('Luna', 'Hill', 'LunaH', 'Pass038'),
('Marco', 'Flores', 'MarcoF', 'Pass039'),
('Nina', 'Green', 'NinaG', 'Pass040'),
('Oscar', 'Adams', 'OscarA', 'Pass041'),
('Penny', 'Nelson', 'PennyN', 'Pass042'),
('Quincy', 'Baker', 'QuincyB', 'Pass043'),
('Rosa', 'Hall', 'RosaH', 'Pass044'),
('Simon', 'Rivera', 'SimonR', 'Pass045'),
('Tara', 'Campbell', 'TaraC', 'Pass046'),
('Uri', 'Mitchell', 'UriM', 'Pass047'),
('Violet', 'Carter', 'VioletC', 'Pass048'),
('Wayne', 'Roberts', 'WayneR', 'Pass049'),
('Ximena', 'Gomez', 'XimenaG', 'Pass050'),
('Yara', 'Phillips', 'YaraP', 'Pass051'),
('Zane', 'Evans', 'ZaneE', 'Pass052'),
('Aiden', 'Turner', 'AidenT', 'Pass053'),
('Brooke', 'Diaz', 'BrookeD', 'Pass054'),
('Caleb', 'Parker', 'CalebP', 'Pass055'),
('Daisy', 'Cruz', 'DaisyC', 'Pass056'),
('Eli', 'Edwards', 'EliE', 'Pass057'),
('Faith', 'Collins', 'FaithC', 'Pass058'),
('Gabe', 'Reyes', 'GabeR', 'Pass059'),
('Hazel', 'Stewart', 'HazelS', 'Pass060'),
('Isaac', 'Morris', 'IsaacM', 'Pass061'),
('Jade', 'Morales', 'JadeM', 'Pass062'),
('Kyle', 'Murphy', 'KyleM', 'Pass063'),
('Lila', 'Cook', 'LilaC', 'Pass064'),
('Miles', 'Rogers', 'MilesR', 'Pass065'),
('Nora', 'Gutierrez', 'NoraG', 'Pass066'),
('Owen', 'Ortiz', 'OwenO', 'Pass067'),
('Piper', 'Morgan', 'PiperM', 'Pass068'),
('Quentin', 'Cooper', 'QuentinC', 'Pass069'),
('Ruby', 'Peterson', 'RubyP', 'Pass070'),
('Sean', 'Bailey', 'SeanB', 'Pass071'),
('Thea', 'Reed', 'TheaR', 'Pass072'),
('Uma', 'Kelly', 'UmaK', 'Pass073'),
('Victor', 'Howard', 'VictorH', 'Pass074'),
('Wendy', 'Ramos', 'WendyR', 'Pass075'),
('Xavier', 'Kim', 'XavierK', 'Pass076'),
('Yolanda', 'Cox', 'YolandaC', 'Pass077'),
('Zach', 'Ward', 'ZachW', 'Pass078'),
('Amber', 'Richardson', 'AmberR', 'Pass079'),
('Blake', 'Watson', 'BlakeW', 'Pass080'),
('Chloe', 'Brooks', 'ChloeB', 'Pass081'),
('Derek', 'Chavez', 'DerekC', 'Pass082'),
('Elena', 'Wood', 'ElenaW', 'Pass083'),
('Felix', 'James', 'FelixJ', 'Pass084'),
('Gina', 'Bennett', 'GinaB', 'Pass085'),
('Hugo', 'Gray', 'HugoG', 'Pass086'),
('Ivy', 'Mendoza', 'IvyM', 'Pass087'),
('Jasper', 'Ruiz', 'JasperR', 'Pass088'),
('Kira', 'Hughes', 'KiraH', 'Pass089'),
('Logan', 'Price', 'LoganP', 'Pass090'),
('Mia', 'Alvarez', 'MiaA', 'Pass091'),
('Noel', 'Castillo', 'NoelC', 'Pass092'),
('Opal', 'Sanders', 'OpalS', 'Pass093'),
('Pierce', 'Patel', 'PierceP', 'Pass094'),
('Queenie', 'Long', 'QueenieL', 'Pass095'),
('Rhett', 'Foster', 'RhettF', 'Pass096'),
('Stella', 'Jimenez', 'StellaJ', 'Pass097'),
('Troy', 'Moreno', 'TroyM', 'Pass098'),
('Unity', 'Wallace', 'UnityW', 'Pass099'),
('Vince', 'Hart', 'VinceH', 'Pass100'),
('Willow', 'Shaw', 'WillowS', 'Pass101'),
('Xander', 'Hunt', 'XanderH', 'Pass102'),
('Yasmine', 'Palmer', 'YasmineP', 'Pass103'),
('Ziggy', 'Duncan', 'ZiggyD', 'Pass104'),
('Aria', 'Ferguson', 'AriaF', 'Pass105'),
('Bryce', 'Nichols', 'BryceN', 'Pass106'),
('Cora', 'Medina', 'CoraM', 'Pass107'),
('Dante', 'Webb', 'DanteW', 'Pass108'),
('Elise', 'Simpson', 'EliseS', 'Pass109'),
('Finn', 'Stevens', 'FinnS', 'Pass110'),
('Gemma', 'Tucker', 'GemmaT', 'Pass111'),
('Hector', 'Porter', 'HectorP', 'Pass112'),
('Isla', 'Hunter', 'IslaH', 'Pass113'),
('Jude', 'Hicks', 'JudeH', 'Pass114'),
('Kaia', 'Crawford', 'KaiaC', 'Pass115'),
('Landon', 'Boyd', 'LandonB', 'Pass116'),
('Mabel', 'Mason', 'MabelM', 'Pass117'),
('Nico', 'Garrett', 'NicoG', 'Pass118'),
('Olive', 'Burton', 'OliveB', 'Pass119'),
('Preston', 'Knight', 'PrestonK', 'Pass120'),
('Quinlan', 'Stone', 'QuinlanS', 'Pass121'),
('Reese', 'Warren', 'ReeseW', 'Pass122'),
('Sage', 'Dixon', 'SageD', 'Pass123'),
('Tobias', 'Rowe', 'TobiasR', 'Pass124'),
('Una', 'Mccoy', 'UnaM', 'Pass125'),
('Vaughn', 'Schultz', 'VaughnS', 'Pass126'),
('Winter', 'Barnett', 'WinterB', 'Pass127'),
('Xyla', 'Obrien', 'XylaO', 'Pass128'),
('York', 'Lynch', 'YorkL', 'Pass129'),
('Zelda', 'Day', 'ZeldaD', 'Pass130'),
('Axel', 'Rush', 'AxelR', 'Pass131'),
('Bree', 'Benson', 'BreeB', 'Pass132'),
('Cruz', 'Daniels', 'CruzD', 'Pass133'),
('Daphne', 'Summers', 'DaphneS', 'Pass134'),
('Emmett', 'Leonard', 'EmmettL', 'Pass135'),
('Flora', 'Payne', 'FloraP', 'Pass136'),
('Grant', 'Sharp', 'GrantS', 'Pass137'),
('Hope', 'Welch', 'HopeW', 'Pass138'),
('Inigo', 'Bush', 'InigoB', 'Pass139'),
('Juno', 'Frank', 'JunoF', 'Pass140'),
('Knox', 'Watts', 'KnoxW', 'Pass141'),
('Leona', 'Manning', 'LeonaM', 'Pass142'),
('Magnus', 'Norris', 'MagnusN', 'Pass143'),
('Nell', 'Hardy', 'NellH', 'Pass144'),
('Orion', 'Carr', 'OrionC', 'Pass145'),
('Pearl', 'Hale', 'PearlH', 'Pass146'),
('Qadir', 'Strong', 'QadirS', 'Pass147'),
('Rosalie', 'Prince', 'RosalieP', 'Pass148'),
('Silas', 'Mccarthy', 'SilasM', 'Pass149'),
('Tessa', 'Bates', 'TessaB', 'Pass150'),
('Uriel', 'Gilmore', 'UrielG', 'Pass151'),
('Valerie', 'Chandler', 'ValerieC', 'Pass152'),
('Weston', 'Gregory', 'WestonG', 'Pass153'),
('Xiomara', 'Lowe', 'XiomaraL', 'Pass154'),
('Yael', 'Bowen', 'YaelB', 'Pass155'),
('Zara', 'Hubbard', 'ZaraH', 'Pass156'),
('Anton', 'Petersen', 'AntonP', 'Pass157'),
('Bianca', 'Mclaughlin', 'BiancaM', 'Pass158'),
('Cedric', 'Gross', 'CedricG', 'Pass159'),
('Delia', 'Booth', 'DeliaB', 'Pass160'),
('Edgar', 'Drake', 'EdgarD', 'Pass161'),
('Freya', 'Swanson', 'FreyaS', 'Pass162'),
('Griffin', 'Koch', 'GriffinK', 'Pass163'),
('Heidi', 'Blair', 'HeidiB', 'Pass164'),
('Idris', 'Saunders', 'IdrisS', 'Pass165'),
('Joy', 'Lacey', 'JoyL', 'Pass166'),
('Kai', 'Velasquez', 'KaiV', 'Pass167'),
('Lena', 'Mcgee', 'LenaM', 'Pass168'),
('Morris', 'Grimes', 'MorrisG', 'Pass169'),
('Naomi', 'Frost', 'NaomiF', 'Pass170'),
('Otto', 'Conner', 'OttoC', 'Pass171'),
('Paloma', 'Koch', 'PalomaK', 'Pass172'),
('Reed', 'Sparks', 'ReedS', 'Pass173'),
('Selena', 'Mcneil', 'SelenaM', 'Pass174'),
('Titus', 'Hardin', 'TitusH', 'Pass175'),
('Ursa', 'Blackwell', 'UrsaB', 'Pass176'),
('Vega', 'Browning', 'VegaB', 'Pass177'),
('Wade', 'Hammond', 'WadeH', 'Pass178'),
('Xia', 'Barber', 'XiaB', 'Pass179'),
('Yves', 'Cline', 'YvesC', 'Pass180'),
('Zion', 'Holden', 'ZionH', 'Pass181'),
('Alma', 'Kramer', 'AlmaK', 'Pass182'),
('Beau', 'Franco', 'BeauF', 'Pass183'),
('Celeste', 'Solis', 'CelesteS', 'Pass184'),
('Dorian', 'Heath', 'DorianH', 'Pass185'),
('Esme', 'Norman', 'EsmeN', 'Pass186'),
('Ford', 'Delacruz', 'FordD', 'Pass187'),
('Gia', 'Rollins', 'GiaR', 'Pass188'),
('Heath', 'Dickerson', 'HeathD', 'Pass189'),
('Ingrid', 'Roman', 'IngridR', 'Pass190'),
('Jonas', 'Herring', 'JonasH', 'Pass191'),
('Kendra', 'Mcintyre', 'KendraM', 'Pass192'),
('Levi', 'Enrique', 'LeviE', 'Pass193'),
('Maeve', 'Christian', 'MaeveC', 'Pass194'),
('Nash', 'Burnett', 'NashB', 'Pass195'),
('Ophelia', 'Stafford', 'OpheliaS', 'Pass196'),
('Porter', 'Clements', 'PorterC', 'Pass197'),
('Raina', 'Dillon', 'RainaD', 'Pass198'),
('Seth', 'Santana', 'SethS', 'Pass199'),
('Thalia', 'Winters', 'ThaliaW', 'Pass200'),
('Upton', 'Moody', 'UptonM', 'Pass201'),
('Vienna', 'Justice', 'ViennaJ', 'Pass202'),
('Wyatt', 'Glass', 'WyattG', 'Pass203'),
('Xylia', 'Livingston', 'XyliaL', 'Pass204'),
('Yuri', 'Wiggins', 'YuriW', 'Pass205'),
('Zinnia', 'Blanchard', 'ZinniaB', 'Pass206'),
('Amos', 'Olson', 'AmosO', 'Pass207'),
('Bonnie', 'Oconnor', 'BonnieO', 'Pass208'),
('Cyrus', 'Stanton', 'CyrusS', 'Pass209'),
('Dawn', 'Shepherd', 'DawnS', 'Pass210'),
('Ellis', 'Cooke', 'EllisC', 'Pass211'),
('Francesca', 'Roach', 'FrancescaR', 'Pass212'),
('Gideon', 'Pham', 'GideonP', 'Pass213'),
('Harmony', 'Merritt', 'HarmonyM', 'Pass214'),
('Ira', 'Brandt', 'IraB', 'Pass215'),
('Josie', 'Campos', 'JosieC', 'Pass216'),
('Kent', 'Duffy', 'KentD', 'Pass217'),
('Lydia', 'Mcconnell', 'LydiaM', 'Pass218'),
('Milo', 'Bauer', 'MiloB', 'Pass219'),
('Nadia', 'Greer', 'NadiaG', 'Pass220'),
('Otis', 'Marks', 'OtisM', 'Pass221'),
('Priya', 'Lamb', 'PriyaL', 'Pass222'),
('Rocco', 'Townsend', 'RoccoT', 'Pass223'),
('Suki', 'Briggs', 'SukiB', 'Pass224'),
('Trent', 'Middleton', 'TrentM', 'Pass225'),
('Unity', 'Jarvis', 'UnityJ', 'Pass226'),
('Vera', 'Logan', 'VeraL', 'Pass227'),
('Winston', 'French', 'WinstonF', 'Pass228'),
('Xara', 'Huber', 'XaraH', 'Pass229'),
('Yosef', 'Gaines', 'YosefG', 'Pass230'),
('Zora', 'Colon', 'ZoraC', 'Pass231'),
('Archer', 'Pruitt', 'ArcherP', 'Pass232'),
('Bethany', 'Crane', 'BethanyC', 'Pass233'),
('Caspian', 'Ponce', 'CaspianP', 'Pass234'),
('Dina', 'Harrell', 'DinaH', 'Pass235'),
('Easton', 'Madden', 'EastonM', 'Pass236'),
('Faye', 'Ashby', 'FayeA', 'Pass237'),
('Gordon', 'Walls', 'GordonW', 'Pass238'),
('Hattie', 'Boyle', 'HattieB', 'Pass239'),
('Ike', 'Frederick', 'IkeF', 'Pass240'),
('Jolene', 'Hendrix', 'JoleneH', 'Pass241'),
('Kieran', 'Spence', 'KieranS', 'Pass242'),
('Lotus', 'Mack', 'LotusM', 'Pass243'),
('Murphy', 'Gentry', 'MurphyG', 'Pass244'),
('Noelle', 'Cordova', 'NoelleC2', 'Pass245'),
('Orla', 'Wynn', 'OrlaW', 'Pass246'),
('Phoenix', 'Dalton', 'PhoenixD', 'Pass247');

-- ============================================
-- Contacts: All assigned to Users 1, 2, and 3
-- Includes "Jo" prefix names for partial match testing
-- and "Sm"/"Al" prefixes for edge case testing
-- ============================================

-- User 1 (RickL) - 25 contacts
INSERT INTO Contacts (FirstName, LastName, Phone, Email, UserID) VALUES
('John', 'Carter', '407-555-0101', 'john.carter@email.com', 1),
('Jones', 'Bradley', '407-555-0102', 'jones.bradley@email.com', 1),
('Joseph', 'Lima', '407-555-0103', 'joseph.lima@email.com', 1),
('Joanne', 'Whitfield', '407-555-0104', 'joanne.whitfield@email.com', 1),
('Alice', 'Wonderland', '123-456-7890', 'alice@example.com', 1),
('Bob', 'Builder', '987-654-3210', 'bob@example.com', 1),
('Sandra', 'Johnson', '407-555-0107', 'sandra.johnson@email.com', 1),
('Mike', 'Jordan', '407-555-0108', 'mike.jordan@email.com', 1),
('Teresa', 'Johansson', '407-555-0109', 'teresa.johansson@email.com', 1),
('Rick', 'Jolly', '407-555-0110', 'rick.jolly@email.com', 1),
('Liam', 'Nguyen', '407-555-0111', 'liam.nguyen@email.com', 1),
('Sofia', 'Johal', '407-555-0112', 'sofia.johal@email.com', 1),
('Noah', 'Patel', '407-555-0113', 'noah.patel@email.com', 1),
('Emma', 'Jopling', '407-555-0114', 'emma.jopling@email.com', 1),
('Oliver', 'Kim', '407-555-0115', 'oliver.kim@email.com', 1),
('Ava', 'Chen', '407-555-0116', 'ava.chen@email.com', 1),
('Mason', 'Johansen', '407-555-0117', 'mason.johansen@email.com', 1),
('Isabella', 'Cruz', '407-555-0118', 'isabella.cruz@email.com', 1),
('Ethan', 'Joyner', '407-555-0119', 'ethan.joyner@email.com', 1),
('Mia', 'Brooks', '407-555-0120', 'mia.brooks@email.com', 1),
('Lucas', 'Fitzgerald', '407-555-0121', 'lucas.fitzgerald@email.com', 1),
('Charlotte', 'Jordan', '407-555-0122', 'charlotte.jordan@email.com', 1),
('Benjamin', 'Walsh', '407-555-0123', 'benjamin.walsh@email.com', 1),
('Amelia', 'Foster', '407-555-0124', 'amelia.foster@email.com', 1),
('James', 'Reeves', '407-555-0125', 'james.reeves@email.com', 1);

-- User 2 (SamS) - 20 contacts
INSERT INTO Contacts (FirstName, LastName, Phone, Email, UserID) VALUES
('Anna', 'Smith', '321-555-0201', 'anna.smith@email.com', 2),
('Brian', 'Smythe', '321-555-0202', 'brian.smythe@email.com', 2),
('Clara', 'Smithson', '321-555-0203', 'clara.smithson@email.com', 2),
('Daniel', 'Smart', '321-555-0204', 'daniel.smart@email.com', 2),
('Evelyn', 'Rhodes', '321-555-0205', 'evelyn.rhodes@email.com', 2),
('Franklin', 'Moses', '321-555-0206', 'franklin.moses@email.com', 2),
('Gloria', 'Chang', '321-555-0207', 'gloria.chang@email.com', 2),
('Harold', 'Joiner', '321-555-0208', 'harold.joiner@email.com', 2),
('Penelope', 'Archer', '321-555-0209', 'penelope.archer@email.com', 2),
('Quinn', 'Blackwood', '321-555-0210', 'quinn.blackwood@email.com', 2),
('Rafael', 'Dominguez', '321-555-0211', 'rafael.dominguez@email.com', 2),
('Sonia', 'Espinoza', '321-555-0212', 'sonia.espinoza@email.com', 2),
('Tyler', 'Finnegan', '321-555-0213', 'tyler.finnegan@email.com', 2),
('Jo', 'Xavier', '321-555-0214', 'jo.xavier@email.com', 2),
('Jonathan', 'Jojo', '321-555-0215', 'jonathan.jojo@email.com', 2),
('Al', 'Smith', '321-555-0216', 'al.smith@email.com', 2),
('Alan', 'Smithson', '321-555-0217', 'alan.smithson@email.com', 2),
('Albert', 'Smits', '321-555-0218', 'albert.smits@email.com', 2),
('Alec', 'Small', '321-555-0219', 'alec.small@email.com', 2),
('Alex', 'Smiley', '321-555-0220', 'alex.smiley@email.com', 2);

-- User 3 (JohnD) - 20 contacts
INSERT INTO Contacts (FirstName, LastName, Phone, Email, UserID) VALUES
('Charlie', 'Chocolate', '555-555-5555', 'charlie@example.com', 3),
('Patricia', 'Jolie', '813-555-0302', 'patricia.jolie@email.com', 3),
('Roberto', 'Jonas', '813-555-0303', 'roberto.jonas@email.com', 3),
('Samantha', 'Frost', '813-555-0304', 'samantha.frost@email.com', 3),
('Tommy', 'Vega', '813-555-0305', 'tommy.vega@email.com', 3),
('Ulrich', 'Johanson', '813-555-0306', 'ulrich.johanson@email.com', 3),
('Wendy', 'Park', '813-555-0307', 'wendy.park@email.com', 3),
('Yolanda', 'Mejia', '813-555-0308', 'yolanda.mejia@email.com', 3),
('Uma', 'Gallagher', '813-555-0309', 'uma.gallagher@email.com', 3),
('Vincent', 'Holloway', '813-555-0310', 'vincent.holloway@email.com', 3),
('Wanda', 'Ingram', '813-555-0311', 'wanda.ingram@email.com', 3),
('Xander', 'Jennings', '813-555-0312', 'xander.jennings@email.com', 3),
('Yara', 'Kaufman', '813-555-0313', 'yara.kaufman@email.com', 3),
('Zeke', 'Lambert', '813-555-0314', 'zeke.lambert@email.com', 3),
('Abigail', 'Monroe', '813-555-0315', 'abigail.monroe@email.com', 3),
('Benedict', 'Norwood', '813-555-0316', 'benedict.norwood@email.com', 3),
('Cassandra', 'Ortega', '813-555-0317', 'cassandra.ortega@email.com', 3),
('Dominic', 'Quintero', '813-555-0318', 'dominic.quintero@email.com', 3),
('Joyce', 'Manning', '813-555-0319', 'joyce.manning@email.com', 3),
('Jordan', 'Blake', '813-555-0320', 'jordan.blake@email.com', 3);